apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-{SERVICE_NAME}
  namespace: default
spec:
  rateLimit:
    average: 30
    burst: 20
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1
